import { yekan } from "@/utils/fonts";
import "./globals.css";

export const Metadata={
  title:"Create Next App",
  description:"Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={yekan.className}>
      {children}
    </body> 
  </html>
  );
}
